{
 "title": "Openshift Puppetmaster",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "environment", "query": "dev,acc,prd,drp" }
  ]
 },
 "panels": [
  {
   "title": "HTTP request processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Percentage processing time" }
   ],
   "targets": [
    {
     "target": "alias(scale(averageSeries(puppetlabs.puppetserver-code-[[environment]]-*.http.puppet-v3-catalog-.*.-percentage),100),'catalog')"
    },
    {
     "target": "alias(scale(averageSeries(puppetlabs.puppetserver-code-[[environment]]-*.http.puppet-v3-file_metadata-.*.-percentage),100),'file metadata')"
    },
    {
     "target": "alias(scale(averageSeries(puppetlabs.puppetserver-code-[[environment]]-*.http.puppet-v3-node-.*.-percentage),100),'node')"
    },
    {
     "target": "alias(scale(averageSeries(puppetlabs.puppetserver-code-[[environment]]-.http.puppet-v3-report-.*.-percentage),100),'report')"
    }
   ]
  },
  {
   "title": "Request Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-catalog-.*.-requests.mean,'catalog')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-report-.*.-requests.mean,'report')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-node-.*.-requests.mean,'node')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadatas-.*.-requests.mean,'file_metadatas')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadata-.*.-requests.mean,'file_metadata')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_content-.*.-requests.mean,'file_content')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.other-requests.mean,'other')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.http.total-requests.mean,'all')"
    }
   ]
  },
  {
   "title": "Request Ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Percentage of Requests" }
   ],
   "targets": [
    {
     "target": "alias(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-catalog-.*.-percentage,100),'catalog')"
    },
    {
     "target": "alias(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-report-.*.-percentage,100),'report')"
    },
    {
     "target": "alias(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-node-.*.-percentage,100),'node')"
    },
    {
     "target": "alias(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadatas-.*.-percentage,100),'file_metadatas')"
    },
    {
     "target": "alias(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadata-.*.-percentage,100),'file_metadata')"
    },
    {
     "target": "alias(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_content-.*.-percentage,100),'file_content')"
    }
   ]
  },
  {
   "title": "Active HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]-*.http.active-requests.count,1)"
    }
   ]
  },
  {
   "title": "JRuby Timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.jruby.borrow-timer.mean,'borrow time')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.jruby.wait-timer.mean,'wait time')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.jruby.lock-held-timer.mean,'lock held time')"
    },
    {
     "target": "alias(puppetlabs.puppetserver-code-[[environment]]*.jruby.lock-wait-timer.mean,'lock wait time')"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]-*.memory.total.committed,1)"
    }
   ]
  },
  {
   "title": "JRubies free vs requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.free-jrubies-histo.mean,1)"
    },
    {
     "target": "aliasByNode(scale(puppetlabs.puppetserver-code-[[environment]]*.jruby.requested-jrubies-histo.mean,-1),1)"
    }
   ]
  }
 ]
}