{
 "title": "Openshift Puppetmaster 2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "environment", "query": "dev,acc,prd,drp" }
  ]
 },
 "panels": [
  {
   "title": "JRuby Usage",
   "type": "graph",
   "description": "* `num jrubies`: number of JRuby instances (constant)\n* `num free jrubies`: number of JRuby instances free\n* `average free jrubies`: average free JRubies over time\n* `average requested jrubies`: average requested JRubies over time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.num-jrubies, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.num-free-jrubies, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.free-jrubies-histo.mean, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*jruby.requested-jrubies-histo, 1, 3)"
    }
   ]
  },
  {
   "title": "JRuby Pool Timers",
   "type": "graph",
   "description": "* `borrow time`: average time a JRuby is borrowed for\n* `wait time`: average time Puppet Server spends waiting to borrow a JRuby to service a request\n* `lock held time`: average time the lock on the JRuby pool is held\n* `lock wait time`: average time Puppet Server spends waiting to acquire the lock",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.borrow-timer.mean, 1, 3, 4)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.wait-timer.mean, 1, 3, 4)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.lock-held-timer.mean, 1, 3, 4)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.jruby.lock-wait-timer.mean, 1, 3, 4)"
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "graph",
   "description": "Heap and non-heap memory used, number of cpus available.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.memory.heap.used, 1, 3, 4)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.memory.non-heap.used, 1, 3, 4)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.num-cpus, 1, 2)"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "description": "Number of active requests and average number of active requests (over ~ 5 minutes).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]-*.http.active-requests.count, 1, 3, 4)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]-*.http.active-histo.mean, 1, 3, 4)"
    }
   ]
  },
  {
   "title": "Request Durations",
   "type": "graph",
   "description": "Average request time by type - time the server spends serving each type of request, including time waiting to acquire a JRuby",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-catalog-.*.-requests.mean, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-report-.*.-requests.mean, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-node-.*.-requests.mean, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadatas-.*.-requests.mean, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadata-.*.-requests.mean, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_content-.*.-requests.mean, 1, 3)"
    },
    {
     "target": "aliasByNode(puppetlabs.puppetserver-code-[[environment]]*.http.total-requests.mean, 1, 3)"
    }
   ]
  },
  {
   "title": "Request Ratios",
   "type": "graph",
   "description": "Percentage of requests handled of each type.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Percentage of Requests" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-catalog-.*.-requests.mean, 100), 1, 3)"
    },
    {
     "target": "aliasByNode(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-report-.*.-requests.mean, 100), 1, 3)"
    },
    {
     "target": "aliasByNode(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-node-.*.-requests.mean, 100), 1, 3)"
    },
    {
     "target": "aliasByNode(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadatas-.*.-requests.mean, 100), 1, 3)"
    },
    {
     "target": "aliasByNode(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_metadata-.*.-requests.mean, 100), 1, 3)"
    },
    {
     "target": "aliasByNode(scale(puppetlabs.puppetserver-code-[[environment]]*.http.puppet-v3-file_content-.*.-requests.mean, 100), 1, 3)"
    }
   ]
  }
 ]
}